version: '3'

services:
    zookeeper-n11:
        image: wurstmeister/zookeeper
        container_name: zookeeper-docker
        ports: 
            - "2181:2181"
    kafka-n11:
        image: wurstmeister/kafka
        container_name: kafka-docker
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-docker:2181