server:
  port: 8080

kafka:
  test-scheduling:
    enabled: true
  topics:
    flattened-event-topic: flattened-event-topic
    aggregation-topic: aggregation-topic
    product-aggregation-topic: product-aggregation-topic
    seller-aggregation-topic: seller-aggregation-topic
  topic-configs:
    - name: flattened-event-topic
      num-partitions: 1
      replication-factor: 1
    - name: aggregation-topic
      num-partitions: 1
      replication-factor: 1
    - name: product-aggregation-topic
      num-partitions: 1
      replication-factor: 1
    - name: seller-aggregation-topic
      num-partitions: 1
      replication-factor: 1

spring:
  kafka:
    client-id: client-group
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      group-id: consumer-group
      max-poll-records:
    streams:
      application-id: stream-app
      properties:
        commit.interval.ms: 100
    listener:
      pollTimeout: 5000
      idleEventInterval: 100000
      concurrency: 5
    bootstrap-servers: localhost:9092